# Generated by Django 6.0 on 2025-12-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_jwt_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jwt_secret',
        ),
    ]
