# Generated by Django 6.0 on 2025-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_jwt_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jwt_secret',
            field=models.CharField(default='secret_key', editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
