# Generated by Django 5.2.9 on 2026-01-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
